# Enable C++ support
language: cpp
# Compiler selection
compiler: g++
# Require sudo for setuid
sudo: required
# Install extra packages
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - autoconf
    - automake
    - gcc-5
    - g++-5
    - libtool
    - make
# Build steps
script:
  - pwd
  - ./autogen.sh
  - ./configure
  - sudo make install
  - slwhttp --help
