language: cpp
compiler: g++-4.9
sudo: required
dist: trusty

script: "sudo apt-get update &> /dev/null && \
         sudo apt-get install -y autoconf automake g++ git libtool make && \
         git submodule update --init && \
         ./autogen.sh && \
         ./configure && \
         sudo make install && \
         slwhttp --help"
