language: cpp
compiler: g++-4.9
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

script: "git submodule update --init && \
         make CXX=g++-4.9 clean all && \
         ./slwhttp --help"
