language: cpp
compiler: g++-4.9
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.9

script: "./configure CXX=g++-4.9 && \
         make install && \
         slwhttp --help"
